### ISSUE TITLE
Issue writing single element to PnPA field of the scan record.

### ISSUE THREAD

**Issue by stmudie** [pyepics/pyepics#12]
Hi,
Firstly, thanks for the great library! I've been using it lately to talk to the scan record. However, I've just discovered a bug if I'm trying to set a single value in one of the scan record Table Mode Position Arrays e.g., P1PA. 

Errors:

Python 2.7.4 (default, Apr  6 2013, 19:04:04) 
[GCC 4.8.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from epics import caput
>>> caput('SCANPV:scan1.P1PA',1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/epics/__init__.py", line 81, in caput
    return thispv.put(value, wait=wait, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/epics/pv.py", line 277, in put
    callback_data=callback_data)
  File "/usr/lib/python2.7/site-packages/epics/ca.py", line 377, in wrapper
    return fcn(*args, **kwds)
  File "/usr/lib/python2.7/site-packages/epics/ca.py", line 1214, in put
    count = min(len(value), count)
TypeError: object of type 'int' has no len()
>>>caput('SCANPV:scan1.P1PA',[1])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/epics/__init__.py", line 81, in caput
    return thispv.put(value, wait=wait, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/epics/pv.py", line 277, in put
    callback_data=callback_data)
  File "/usr/lib/python2.7/site-packages/epics/ca.py", line 377, in wrapper
    return fcn(*args, **kwds)
  File "/usr/lib/python2.7/site-packages/epics/ca.py", line 1235, in put
    data[0] = type(data[0])(value)
TypeError: float() argument must be a string or a number

So its seems the code here doesn't check for a non-array? I get the same error if I use the PV object.

Thanks,

Stephen Mudie
SAXS/WAXS Beamline
Australian Synchrotron

**Comment by newville** [comment]
fixed
