### ISSUE TITLE
TypeError: _handle_events() got an unexpected keyword argument 'pvname'

### ISSUE THREAD

**Issue by hinxx** [pyepics/pyepics#136]
I got these messages the other day:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.5/site-packages/epics/ca.py", line 539, in _onMonitorEvent
    args.usr(value=value, **kwds)
TypeError: _handle_events() got an unexpected keyword argument 'pvname'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.5/site-packages/epics/ca.py", line 539, in _onMonitorEvent
    args.usr(value=value, **kwds)
TypeError: _run_callback() got an unexpected keyword argument 'pvname'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.5/site-packages/epics/ca.py", line 539, in _onMonitorEvent
    args.usr(value=value, **kwds)
TypeError: _handle_events() got an unexpected keyword argument 'pvname'
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.5/site-packages/epics/ca.py", line 539, in _onMonitorEvent
    args.usr(value=value, **kwds)
TypeError: _run_callback() got an unexpected keyword argument 'pvname'
```

How to solve or should I be worried at all?

**Comment by newville** [comment]
Hi Hinko,
Can you provide a simple example that shows the problem?   

I would guess that the definition of `handle_events()` (which must be in your code) is not expecting an argument called `pvname`.   Since the contents of a PVs "metadata" changes with DBR type, and since there might be a fair amount of metadata that you don't actually care about (at least for every monitor event), it's recommended to define a callback to take `**kws`:

```
def my_callback(pvname=None, value=None, status=None, **kws):
     ....

my_pv = epics.PV(my_pvname, callback=my_callback)
```

**Comment by hinxx** [comment]
Hi Matt,
Thanks for the pointers!

I have this code:

```
self.pv = epics.PV(cfg['CHARGE'], auto_monitor=True, callback=self.onPVValueChange)
...
def onPVValueChange(self, pvname=None, **kw):
    logging.debug('PV %s value changed' % (pvname))
```

This is the only place I try to use auto_monitor feature, I have other PVs but I useg pv.get() instead on those.

Looking at the [ca.py, lines 536:539](https://github.com/pyepics/pyepics/blob/master/epics/ca.py#L539) it seems that the args.usr() call does not set 'pvname', while my callback expects it. I'll remove 'pvname' argument from my callback to see if it helps.

**Comment by newville** [comment]
Hi Hinko, 

Hm, I'm not sure why you're getting that.   This works for me:

```python
import epics
class PVTester:
    def __init__(self, pvnames):
        self.pvs = []
        for p in pvnames:
            self.pvs.append(epics.PV(p, auto_monitor=True,
                                     callback=self.onPVValueChanges))

    def onPVValueChanges(self, pvname=None, **kws):
        print(" change ", pvname, kws['value'])

tester = PVTester(['Py:ao1', 'Py:ao2'])
while True:
    epics.poll()
```

Does that work for you or help point out what might be different for you?

**Comment by hinxx** [comment]
I will just run this basic test script and leave it for a while, thank you!

The thing is that the problem is not manifested 100% of the time and might be caused by something else.

As it seems, I just identified this issue on our network - https://epics.anl.gov/tech-talk/2017/msg00723.php. I can see lots of zero length PV names flying by, highly likely not the ones I want to listen to, but in any case could this be related to the problem at hand?

**Comment by hinxx** [comment]
Running:

```
[hinkokocevar@pbi-softioc tests]$ python3.5 test_pvname.py
**** The executable "caRepeater" couldn't be located
**** because of errno = "No such file or directory".
**** You may need to modify your PATH environment variable.
**** Unable to start "CA Repeater" process.
 change  LEBT-010:PBI-BCM-001:AI5-IPCH-RBV -0.2776075732421875
 change  ISrc-010:PBI-BCM-001:AI4-IPCH-RBV 0.008697801513671876
 change  ISrc-010:PBI-BCM-001:AI4-IPCH-RBV 0.29467349609375004
 change  LEBT-010:PBI-BCM-001:AI5-IPCH-RBV 1.1857459948730469
 change  ISrc-010:PBI-BCM-001:AI4-IPCH-RBV -0.5852413818359374
 change  LEBT-010:PBI-BCM-001:AI5-IPCH-RBV -0.5910000561523436
 change  ISrc-010:PBI-BCM-001:AI4-IPCH-RBV -0.14488114990234374

```

**Comment by newville** [comment]
@hinxx  Oh, yeah a zero-length PV name could definitely cause problems!   I don't think we really test for that.   I'm also not entirely sure how that can happen!

**Comment by hinxx** [comment]
I have been running the test script over the weekend and there were no exceptions reported. Here is the script:

```
$ cat test_pvname.py 
import epics

# debugging the https://github.com/pyepics/pyepics/issues/136


class PVTester:
    def __init__(self, pvnames):
        self.pvs = []
        for p in pvnames:
            self.pvs.append(epics.PV(p, auto_monitor=True,
                                     callback=self.onPVValueChanges))

    def onPVValueChanges(self, pvname=None, **kws):
        print(" change ", pvname, kws['value'])

tester = PVTester(['LEBT-010:PBI-BCM-001:AI5-IPCH-RBV', 'ISrc-010:PBI-BCM-001:AI4-IPCH-RBV'])

while True:
    epics.poll()
```

**Comment by klauer** [comment]
The original traceback in the issue reported here:
```python
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/usr/lib/python3.5/site-packages/epics/ca.py", line 539, in _onMonitorEvent
    args.usr(value=value, **kwds)
TypeError: _run_callback() got an unexpected keyword argument 'pvname'
```

Indicates that the function specified to `ca.create_subscription` doesn't expect the `pvname` kwarg. As this is almost certainly user error, I'm closing this.
