### ISSUE TITLE
pyepics and pcaspy not compatible on Windows since pyepics3.3.2?

### ISSUE THREAD

**Issue by ghost** [pyepics/pyepics#176]
I am not sure if this is really a pyepics issue or rather a pcaspy one, but I ran into it when I updated pyepics to version 3.4.0, so I thought I start here...
The host is Windows 10 64bit, the issue does not seem to exist on linux. In pyepics 3.3.1 this issue did not exist, but I actually need 3.4.0.
The problem is reproducible like this (provided latest pyepics and pcaspy versions):
```
>>> from pcaspy import SimpleServer, Driver
>>> from epics import *
>>> ca.initialize_libca()
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\epics\ca.py", line 373, in initialize_libca
    libca = load_dll(find_libca())
  File "C:\Program Files\Python36\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\epics\ca.py", line 373, in initialize_libca
    libca = load_dll(find_libca())
  File "C:\Program Files\Python36\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Program Files\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\epics\ca.py", line 375, in initialize_libca
    raise ChannelAccessException('loading Epics CA DLL failed: ' + str(exc))
epics.ca.ChannelAccessException: loading Epics CA DLL failed: [WinError 127] The specified procedure could not be found
```

A related error happens when pcaspy is imported after pyepics:
```
>>> from epics import ca
>>> ca.initialize_libca()
<WinDLL 'C:\Program Files\Python36\lib\site-packages\epics\clibs\win64\ca.dll', handle 7fff03000000 at 0x23268cbf2b0>
>>> from pcaspy import Driver, SimpleServer
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\pcaspy\cas.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python36\lib\site-packages\pcaspy\__init__.py", line 1, in <module>
    from .driver import Driver, SimpleServer, PVInfo, SimplePV
  File "C:\Program Files\Python36\lib\site-packages\pcaspy\driver.py", line 1, in <module>
    from . import cas
  File "C:\Program Files\Python36\lib\site-packages\pcaspy\cas.py", line 17, in <module>
    _cas = swig_import_helper()
  File "C:\Program Files\Python36\lib\site-packages\pcaspy\cas.py", line 16, in swig_import_helper
    return importlib.import_module('_cas')
  File "C:\Program Files\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_cas'
```

As a "quick fix" it works to overwrite the pyepics provided DLLs with the pcaspy ones.

**Comment by newville** [comment]
@mdoor Hm, sorry for the trouble -- I'm not sure what the problem might be.   To be clear, I'm using pyepics 3.4.0 on Windows 7 and 10 regularly ("in production"), so I think it should definitely work.    And it looks like it would if you did not also want to use pcaspy.   

I don't regularly use pcaspy and I'm not sure I've ever tried it on Windows. Perhaps pcaspy is also providing a version of `ca.dll` -- can you verify?  I don't know that for sure, but I can believe it would cause problems.

**Comment by newville** [comment]
@mdoor  As a follow up, it does look like the binary installer for pcaspy comes with its own version of ca.dll and Com.dll on Windows and tries to load them on import.  That is sort of unfortunate.  

It might work to set PYPEPICS_LIBCA to point to the version that comes with pcaspy.  That's a bit kludgy.

I don't know if are any options within pcaspy to do similar things.  It sort of looks like they are using SWIG and importing a `_cas.pyd` file.  It could be that this dll is linked to ca.dll and Com.dll.   But, I'm not 100% sure I have that right.

**Comment by mdoor** [comment]
@newville Sorry for my late response and thanks for your suggestins and opening this issue at pcaspy. The solution with the PYEPICS_LIBCA variable works for me for now 👍

The supplied DLLs from pcaspy are a little older than the ones from pyepics. Could this result in errors in pyepics 3.4.0 or is it "safe" to use with EPICS 3.14 DLLs?

**Comment by newville** [comment]
@mdoor I think it should be fine to use the 3.14 DLLs.  I believe we aren't yet relying on any features introduced after 3.13 even. 

I would still say it unfortunate that this hack is *required*, and I can believe that it would imply that problems could arise on other platforms too.    It may be that pyepics should go down the path of deliberately renaming ca.dll / libca.so to be pyepics-specific (such as `ca_pyepics.dll` / `libca_pyepics.so`, etc).   That renaming would likely prevent this and other potential cases of collisions (like #173, there with `pydevsup`) with another imported library or part of the process wanting to access a CA library.

**Comment by vstadnytskyi** [comment]
I am getting a similar error reported earlier in this issue but it happens somewhere inside. I don't import `pcaspy` though.

```
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\epics\ca.py", line 226, in initialize_libca
    load_dll(find_libCom())
  File "C:\Python37\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\epics\ca.py", line 226, in initialize_libca
    load_dll(find_libCom())
  File "C:\Python37\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\wx\core.py", line 3259, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Python37\lib\site-packages\epics\wx\wxlib.py", line 177, in SetPV
    self.pv = epics.get_pv(pv, form=form)
  File "C:\Python37\lib\site-packages\epics\pv.py", line 44, in get_pv
    context = ca.current_context()
  File "C:\Python37\lib\site-packages\epics\ca.py", line 382, in wrapper
    initialize_libca()
  File "C:\Python37\lib\site-packages\epics\ca.py", line 229, in initialize_libca
    raise ChannelAccessException('loading Epics CA DLL failed: ' + str(exc))
epics.ca.ChannelAccessException: loading Epics CA DLL failed: [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\epics\ca.py", line 226, in initialize_libca
    load_dll(find_libCom())
  File "C:\Python37\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\epics\ca.py", line 226, in initialize_libca
    load_dll(find_libCom())
  File "C:\Python37\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\wx\core.py", line 3259, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "C:\Python37\lib\site-packages\epics\wx\wxlib.py", line 177, in SetPV
    self.pv = epics.get_pv(pv, form=form)
  File "C:\Python37\lib\site-packages\epics\pv.py", line 44, in get_pv
    context = ca.current_context()
  File "C:\Python37\lib\site-packages\epics\ca.py", line 382, in wrapper
    initialize_libca()
  File "C:\Python37\lib\site-packages\epics\ca.py", line 229, in initialize_libca
    raise ChannelAccessException('loading Epics CA DLL failed: ' + str(exc))
epics.ca.ChannelAccessException: loading Epics CA DLL failed: [WinError 126] The specified module could not be found
```

My code:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#import os
#import pcaspy
#os.environ['PYEPICS_LIBCA'] = os.path.join(os.path.dirname(pcaspy.__file__), "ca.dll")

import epics
import wx
import epics.wx
from logging import debug,warn,info,error

__version__ = "0.0.0" #initial

class PanelTemplate(wx.Frame):

        title = "GUI Panel Template"

        def __init__(self):
            wx.Frame.__init__(self, None, wx.ID_ANY, title=self.title, style=wx.DEFAULT_FRAME_STYLE)
            self.panel=wx.Panel(self, -1, size = (200,75))
            self.Bind(wx.EVT_CLOSE, self.OnQuit)

            self.initialize_GUI()
            self.SetBackgroundColour(wx.Colour(255,255,255))
            self.Centre()
            self.Show()

        def OnQuit(self,event):
            """
            orderly exit of Panel if close button is pressed
            """
            self.Destroy()
            del self

        def initialize_GUI(self):
            """
            """
            sizer = wx.GridBagSizer(hgap = 5, vgap = 5)
            self.label ={}
            self.field = {}
            self.sizer = {}
            main_sizer = wx.BoxSizer(wx.VERTICAL)
            topSizer = wx.BoxSizer(wx.VERTICAL)



            self.sizer[b'x'] = wx.BoxSizer(wx.HORIZONTAL)
            self.label[b'x'] = wx.StaticText(self.panel, label= 'X value:', style = wx.ALIGN_CENTER)
            self.field[b'x'] = epics.wx.PVText(self.panel, pv='random_walk:x',minor_alarm = wx.Colour(5, 6, 7),auto_units = True)
            self.sizer[b'x'].Add(self.label[b'x'] , 0)
            self.sizer[b'x'].Add(self.field[b'x'] , 0)

            self.sizer[b't'] = wx.BoxSizer(wx.VERTICAL)
            self.label[b't'] = wx.StaticText(self.panel, label= 'Time of last update:', style = wx.ALIGN_CENTER)
            self.field[b't'] = epics.wx.PVText(self.panel, pv='random_walk:t',minor_alarm = wx.Colour(5, 6, 7),auto_units = True)
            self.sizer[b't'].Add(self.label[b't'] , 0)
            self.sizer[b't'].Add(self.field[b't'] , 0)


            main_sizer.Add(self.sizer[b'x'],0)
            main_sizer.Add(self.sizer[b't'],0)


            self.Center()
            self.Show()
            topSizer.Add(main_sizer,0)


            self.panel.SetSizer(topSizer)
            topSizer.Fit(self)
            self.Layout()
            self.panel.Layout()
            self.panel.Fit()
            self.Fit()

if __name__ == '__main__':
    from pdb import pm
    import logging
    from tempfile import gettempdir

    app = wx.App(redirect=False)
    panel = PanelTemplate()

    app.MainLoop()

```

**Comment by newville** [comment]
@vstadnytskyi  You keep asserting that behavior you see is related to a completely different issue. Please stop doing that.  If you are not importing `pcaspy` then the problem you are having has nothing to do with this issue.

Your script runs fine for me when I replace your PVs with ones that are connected for me.

I suggest you see what happens if you do:

     import epics
     p  = epics.get_pv('random_walk:x')
     print(p, p.get())

If that fails, then pcaspy and wx stuff are clearly not involved, and you can check why pyepics is not working for you. You might also just try:

    import epics
    epics.ca.initialize_libca()

which will load and return LIBCA, and so tell you exactly which file is used.

**Comment by vstadnytskyi** [comment]
> @vstadnytskyi You keep asserting that behavior you see is related to a completely different issue. Please stop doing that. If you are not importing `pcaspy` then the problem you are having has nothing to do with this issue.

But it manifests in the same way, very similar tracebacks. Would you prefer me to create a new issue like "pyepics not compatible on Windows since pyepics3.3.2?"

> 
> Your script runs fine for me when I replace your PVs with ones that are connected for me.
> 
> I suggest you see what happens if you do:
> 
> ```
>  import epics
>  p  = epics.get_pv('random_walk:x')
>  print(p, p.get())
> ```
> 
> If that fails, then pcaspy and wx stuff are clearly not involved, and you can check why pyepics is not working for you. You might also just try:
> 
> ```
> import epics
> epics.ca.initialize_libca()
> ```
> 
> which will load and return LIBCA, and so tell you exactly which file is used.



Here is what happened. 
1. I was not importing pcaspy but I got the same error(see above) reported by mdoor (see the first post). The fix to his problem was provided here https://github.com/paulscherrerinstitute/pcaspy/issues/64
2. I have applied the fix and got a different error and I have reported in pcaspy project that the fix didn't work.


Here what I have tried:

```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import epics
>>> p  = epics.get_pv('random_walk:x')
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\epics\ca.py", line 226, in initialize_libca
    load_dll(find_libCom())
  File "C:\Python37\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\epics\ca.py", line 226, in initialize_libca
    load_dll(find_libCom())
  File "C:\Python37\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    p  = epics.get_pv('random_walk:x')
  File "C:\Python37\lib\site-packages\epics\pv.py", line 44, in get_pv
    context = ca.current_context()
  File "C:\Python37\lib\site-packages\epics\ca.py", line 382, in wrapper
    initialize_libca()
  File "C:\Python37\lib\site-packages\epics\ca.py", line 229, in initialize_libca
    raise ChannelAccessException('loading Epics CA DLL failed: ' + str(exc))
epics.ca.ChannelAccessException: loading Epics CA DLL failed: [WinError 126] The specified module could not be found
>>> 
```

So somehow installation of pyepics didn't go right, is it correct?
```
>>> epics.ca.initialize_libca()
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\epics\ca.py", line 226, in initialize_libca
    load_dll(find_libCom())
  File "C:\Python37\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
Traceback (most recent call last):
  File "C:\Python37\lib\site-packages\epics\ca.py", line 226, in initialize_libca
    load_dll(find_libCom())
  File "C:\Python37\lib\ctypes\__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    epics.ca.initialize_libca()
  File "C:\Python37\lib\site-packages\epics\ca.py", line 229, in initialize_libca
    raise ChannelAccessException('loading Epics CA DLL failed: ' + str(exc))
epics.ca.ChannelAccessException: loading Epics CA DLL failed: [WinError 126] The specified module could not be found
>>> 
```

**Comment by newville** [comment]
@vstadnytskyi 
>> @vstadnytskyi You keep asserting that behavior you see is related to a completely different issue. Please stop doing that. If you are not importing pcaspy then the problem you are having has nothing to do with this issue.

> But it manifests in the same way, very similar tracebacks. 

Actually they are different.

> Would you prefer me to create a new issue like "pyepics not compatible on Windows since pyepics3.3.2?"

I would prefer you to create a new issue like "cannot load libca on Windows".  Well, unless you are saying that it *does* work with `pyepics3.3.2` and now *does not* work with `pyepics3.4`.  That is, I want you issue to be complete and accurate.  Again, your issue is not at all related to `pcaspy`.

Yeah, it looks like you need to re-install `pyepics`.  Which is weird because your installation of `pcaspy` was also broken.  Something seems very wrong, almost as if you installed them incorrectly or moved around files in the installation location.

**Comment by vstadnytskyi** [comment]
> @vstadnytskyi
> 
> > > @vstadnytskyi You keep asserting that behavior you see is related to a completely different issue. Please stop doing that. If you are not importing pcaspy then the problem you are having has nothing to do with this issue.
> 
> > But it manifests in the same way, very similar tracebacks.
> 
> Actually they are different.
> 
> > Would you prefer me to create a new issue like "pyepics not compatible on Windows since pyepics3.3.2?"
> 
> I would prefer you to create a new issue like "cannot load libca on Windows". Well, unless you are saying that it _does_ work with `pyepics3.3.2` and now _does not_ work with `pyepics3.4`. That is, I want you issue to be complete and accurate. Again, your issue is not at all related to `pcaspy`.
> 
> Yeah, it looks like you need to re-install `pyepics`. Which is weird because your installation of `pcaspy` was also broken. Something seems very wrong, almost as if you installed them incorrectly or moved around files in the installation location.

The windows machine I originally tested my code has some major problems with how python installed. I have tried the same code on a different windows machine and it worked.
Thanks!
