### ISSUE TITLE
epics.PV auto_monitor and count bug

### ISSUE THREAD

**Issue by klauer** [pyepics/pyepics#20]
An epics.PV of a waveform with automonitor enabled can yield this error when first trying to use get(count=x) with this exception:

``` python
Traceback (most recent call last):
  File "mca_test.py", line 14, in <module>
    print(mca, mca.get(count=10))
  File "/home/nanopos/ecli/epics/pv.py", line 226, in get
    (count is not None and count > len(self._args['value']))):
TypeError: object of type 'int' has no len()
```

Here's an example script:

``` python
import epics

print(epics.caget('scaler1:mca1')[:10])

mca_records = [epics.PV('scaler1:mca%d' % i, auto_monitor=False) for i in range(1, 5)]

for mca in mca_records:
    print(mca, mca.get(count=10))

mca_records = [epics.PV('scaler1:mca%d' % i) for i in range(1, 5)]

for mca in mca_records:
    print(mca, mca.get(count=10))
```

And the raw output:

```
[0 0 0 0 0 0 0 0 0 0]
(<PV 'scaler1:mca1', count=10000/10000, type=long, access=read/write>, array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))
(<PV 'scaler1:mca2', count=10000/10000, type=long, access=read/write>, array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))
(<PV 'scaler1:mca3', count=10000/10000, type=long, access=read/write>, array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))
(<PV 'scaler1:mca4', count=10000/10000, type=long, access=read/write>, array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))
Traceback (most recent call last):
  File "mca_test.py", line 14, in <module>
    print(mca, mca.get(count=10))
  File "/home/nanopos/ecli/epics/pv.py", line 226, in get
    (count is not None and count > len(self._args['value']))):
TypeError: object of type 'int' has no len()
```

A possible fix would be to add a _cached_length property and compare the count to this:

``` python
      @property
      def _cached_length(self):
          """
          Length of cached value
          """
          try:
              return len(self._args['value'])
          except:
              return 1
```

As a note, though, this does not happen on all waveform records. This only appears to happen when used with slower CA servers such as those on VME, though using `wait_for_connection` and such had no effect.

**Comment by klauer** [comment]
This was fixed in aa5451dcb5a0ca706421493a68aaea47b40fe927.
