### ISSUE TITLE
libca.so cannot be found on RPi 64bit

### ISSUE THREAD

**Issue by Septyawan24** [pyepics/pyepics#238]
I new to EPICS and I try to install Pyepics on my Raspberry Pi4 with RaspiOS 64 bit also python 3.9. but when I try to run simple caget command, I found this error:
```
Traceback (most recent call last):
  File "/home/kkpr01/.local/lib/python3.9/site-packages/epics/ca.py", line 380, in initialize_libca
    libca = load_dll(find_libca())
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/kkpr01/.local/lib/python3.9/site-packages/epics/clibs/linux64/libca.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/kkpr01/.local/lib/python3.9/site-packages/epics/ca.py", line 380, in initialize_libca
    libca = load_dll(find_libca())
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/kkpr01/.local/lib/python3.9/site-packages/epics/clibs/linux64/libca.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kkpr01/.local/lib/python3.9/site-packages/epics/__init__.py", line 160, in caget
    thispv = get_pv(pvname, timeout=connection_timeout, connect=True)
  File "/home/kkpr01/.local/lib/python3.9/site-packages/epics/pv.py", line 113, in get_pv
    if ca.current_context() is None:
  File "/home/kkpr01/.local/lib/python3.9/site-packages/epics/ca.py", line 550, in wrapper
    initialize_libca()
  File "/home/kkpr01/.local/lib/python3.9/site-packages/epics/ca.py", line 382, in initialize_libca
    raise ChannelAccessException('loading Epics CA DLL failed: ' + str(exc))
epics.ca.ChannelAccessException: loading Epics CA DLL failed: /home/kkpr01/.local/lib/python3.9/site-packages/epics/clibs/linux64/libca.so: cannot open shared object file: No such file or directory
```

I thought that libca.so is not exist, but it is there. here the result from find command:

```
test01@raspberrypi:~ $ find . -iname libca.so
./App/EPICS/epics-base/lib/linux-aarch64/libca.so
./.local/lib/python3.9/site-packages/epics/clibs/linux64/libca.so
./.local/lib/python3.9/site-packages/epics/clibs/linux32/libca.so
./.local/lib/python3.9/site-packages/epics/clibs/linuxarm/libca.so
```
did I do something wrong? Kindly help. Thank you.

**Comment by newville** [comment]
@Septyawan24 Sorry for the trouble.  I am pretty sure that the problem is that the version of libca we distribute for "linuxarm" is 32-bit, but 64-bit.

 if you have libca.so built for 64-bit ARM Linux for raspberry pi, you could point the environment variable  `PYEPICS_LIBCA` to that file before using CA.  Perhaps setting that to the `.../EPICS/epics-base/lib/linux-aarch64/libca.so` would work -- it's worth a try: 

export PYEPICS_LIBCA=<fullpath..>/epics-base/lib/linux-aarch64/libca.so

I have to admit that I have not kept up with epics on raspberry pi very closely, and I am not certain what the best build of libca to use for 64-bit rpi.   Perhaps @prjemian knows?    Should we include a "linux-aarch64"?   We should probably think about updating all of the libca binaries....

**Comment by Septyawan24** [comment]
@newville Thanks for the response, setting PYEPICS_LIBCA solve my problem. I tested for other 64bit OS for raspberry pi and it work without problem. Thank you.
