### ISSUE TITLE
TypeError in ca.withConnectedCHID wrapper

### ISSUE THREAD

**Issue by ptowalski** [pyepics/pyepics#32]
Got this error today:

````
Exception in thread Thread-630:
Traceback (most recent call last):
  File "C:\DATEN\Programme\WinPython-32bit-3.3.5.0\python-3.3.5\lib\threading.py", line 901, in _bootstrap_inner
    self.run()
  File "C:\DATEN\Programme\WinPython-32bit-3.3.5.0\python-3.3.5\lib\threading.py", line 858, in run
    self._target(*self._args, **self._kwargs)
  File "wfh.py", line 1126, in to_epics
    #print(i)
  File "C:\DATEN\Programme\WinPython-32bit-3.3.5.0\python-3.3.5\lib\site-packages\pyepics-3.2.3-py3.3.egg\epics\pv.py", line 282, in put
    callback_data=callback_data)
  File "C:\DATEN\Programme\WinPython-32bit-3.3.5.0\python-3.3.5\lib\site-packages\pyepics-3.2.3-py3.3.egg\epics\ca.py", line 404, in wrapper
    chid, timeout))
TypeError: %d format: a number is required, not c_long
````
I think there is an issue with the data type "c_long" while formating the exception string.

Anyway I think there is a missing parameter (chid) in the fmt-string (ca.py, line 397ff):
````
    timeout = kwds.get('timeout', DEFAULT_CONNECTION_TIMEOUT)
    fmt ="%s: timed out waiting for chid to connect (%d seconds)"
    if not connect_channel(chid, timeout=timeout):
        raise ChannelAccessException(fmt % (fcn.__name__,
                                            chid, timeout))
````

**Comment by newville** [comment]
@ptowalski  Thanks!  This is now fixed in c30cb2fe51af045c1414472aedb68696c02940f0 and test added.
