### ISSUE TITLE
Exception in monitor callback

### ISSUE THREAD

**Issue by pfpmeijers** [pyepics/pyepics#34]
When I reload all my modules in an embedded Python interpreter, including the epics module, then I get following errors: 

Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "/usr/local/lib/python2.7/dist-packages/pyepics-b7d26fe9a057be74348eee93a3cab7ab51636d51-py2.7.egg/epics/ca.py", line 456, in _onMonitorEvent
    if dbr.PY64_WINDOWS:   args = args.contents
AttributeError: 'NoneType' object has no attribute 'PY64_WINDOWS'

Hence, the global dbr object as imported in ca.py becomes None for some reason.

The channel values that I am monitoring still come through. But the control vars don't.
The pv.get_ctrlvars(timeout=0.1) returns None, while orginally after the initial load of the modules this works well.

Anyone a clue?

**Comment by pfpmeijers** [comment]
Found a solution by doing a finalize_libca() before reopening the module. Occassionally I still get other exception (see below) from the _onMonitorEvent function. But I will dig into that some more first.
